// +build !skippackr
// Code generated by github.com/gobuffalo/packr/v2. DO NOT EDIT.

// You can use the "packr2 clean" command to clean up this,
// and any other packr generated files.
package packrd

import (
	"github.com/gobuffalo/packr/v2"
	"github.com/gobuffalo/packr/v2/file/resolver"
)

var _ = func() error {
	const gk = "6455c51ff32bce221a80fb856254a82f"
	g := packr.New(gk, "")
	hgr, err := resolver.NewHexGzip(map[string]string{
		"683efbe2974a022ac183e1a06ad0f76c": "1f8b08000000000000ff5cce310ac2401085e17e4e31a5a239415a2d6cac22d82d6be6c52cc4dd656631787b312ac6bceac1d7fc55c59b5bb8aa2fe053266a15af5bfc6500676f3626155a113373105eec706cb613f5de7a973ad785016f6af6e78f19a2409d175198fd9ba245b8cff56788ad3e7231f7cd988cd635d1bc7a97c648249af2a2ba7e060000ffff60b7ca3ddc000000",
	})
	if err != nil {
		panic(err)
	}
	g.DefaultResolver = hgr

	func() {
		b := packr.New("migrations", "./migrations")
		b.SetResolver("001_inital.sql", packr.Pointer{ForwardBox: gk, ForwardPath: "683efbe2974a022ac183e1a06ad0f76c"})
	}()
	return nil
}()
