// +build !skippackr
// Code generated by github.com/gobuffalo/packr/v2. DO NOT EDIT.

// You can use the "packr2 clean" command to clean up this,
// and any other packr generated files.
package packrd

import (
	"github.com/gobuffalo/packr/v2"
	"github.com/gobuffalo/packr/v2/file/resolver"
)

var _ = func() error {
	const gk = "6455c51ff32bce221a80fb856254a82f"
	g := packr.New(gk, "")
	hgr, err := resolver.NewHexGzip(map[string]string{
		"683efbe2974a022ac183e1a06ad0f76c": "1f8b08000000000000ff64cf3d0ec2300c86e1dda7f008829ea02b57608ed2e66b1ba924916d517a7bc49f08c593a567b0dfa6e1c3258ee20d7c2e44bde0b19aef6670f1aa4b96403b62668e8137d3c531263b3e75f23ab93cb821ce78a9e1f636450a10e74310a8fe9aa047bcd6fa35a45ed662ea3e9f54666bc1ff3ddab74475d4292f8928482e9ba8f61e0000ffff2200f0dafb000000",
	})
	if err != nil {
		panic(err)
	}
	g.DefaultResolver = hgr

	func() {
		b := packr.New("migrations", "./migrations")
		b.SetResolver("001_inital.sql", packr.Pointer{ForwardBox: gk, ForwardPath: "683efbe2974a022ac183e1a06ad0f76c"})
	}()
	return nil
}()
